### ISSUE TITLE
can't access sitemap.xml

### ISSUE THREAD

**Issue by findthebug** [omz13/kirby3-xmlsitemap#24]
Kirby 3.1.
xmlsitemap: 1.1.5
Installed via composer.

try to access the sitemap via sitemap.xml, but still get an error. See attachment.
- there are 4 pages listed in the backend
- default, no config set

`This page contains the following errors:
error on line 2 at column 6: XML declaration allowed only at the start of the document`

<img width="1502" alt="Bildschirmfoto 2019-03-21 um 15 43 41" src="https://user-images.githubusercontent.com/5121132/54761962-709d3d80-4bf3-11e9-9538-d1b0de5966f2.png">

here the cache file
[1.1.5-sitemap-adb8d9ce0acf8d9fe892f839473335c3.cache.zip](https://github.com/omz13/kirby3-xmlsitemap/files/2992672/1.1.5-sitemap-adb8d9ce0acf8d9fe892f839473335c3.cache.zip)

<img width="1525" alt="Bildschirmfoto 2019-03-21 um 16 44 24" src="https://user-images.githubusercontent.com/5121132/54764779-b14b8580-4bf8-11e9-9cd1-aa3540d52489.png">

-> maybe i miss something. i tested this with a custom installation which output the error above.

**Comment by omz13** [comment]
For some reason, there is an empty line being inserted before the xml content. Does this happen on the pages in your site?

**Comment by luxlogica** [comment]
I'm getting the same error... :( 

Site currently has some dummy content/pages, but no templates - I'm building the blueprints and setting everything up while the frontend is still being finished. 

Cannot access _sitemap.xml_.

----
Ok, I've done a little troubleshooting on my end, and in my case, the pesky empty line was coming from my _'config.php'_ file - it had an empty line at the very beginning of it, that was causing the issue.

While I was troubleshooting, I downloaded both a copy of the latest _starterkit_ and _plainkit_, and installed the plugin there - it works without issues. It is likely, therefore, that this issue is being caused by an empty line being left at the beginning of a PHP file somewhere..

Hopefully, @findthebug's issue is going to be just as easy to pinpoint! ;-)

**Comment by findthebug** [comment]
thanks for the input. meanwhile i also found the issue in my installation. for some reason i have a file in **site/models/default.php** , and this has two emty lines in it. delete these lines or remove the file complete and the xml is working as expected.

**Comment by omz13** [comment]
Thanks @luxlogica for your troubleshooting.
Good to hear @findthebug that you found the issue with your installation.

**Comment by DominiqueVial** [comment]
Arhhhh! I have the very same problem. And none of the answer here solved it.
This occur both on local and distant website...

What a pity: looking for empty lines in some files...  :-(

---

Gotcha! 2 empty lines before `<?php`in on some `index.php` file related to a plugin...
