### ISSUE TITLE
XML Error

### ISSUE THREAD

**Issue by Werbschaft** [omz13/kirby3-xmlsitemap#25]
No matter what I try, the sitemap will not work. The strange one is that my site isn't located in http://localhost:8888/sitemap.xsl as in the error appears. Currentyl the site is under http://localhost:8888/dev/

Is there a known bug or error?

```
XML-Verarbeitungsfehler: Syntax-Fehler
Adresse: http://localhost:8888/sitemap.xsl
Zeile Nr. 1, Spalte 50:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
-------------------------------------------------^
```

**Comment by omz13** [comment]
I am confused about where the base (index) of your kirby site lives... is it http://localhost:8888/  or http://localhost:8888/dev (you really want to run it under a subfolder?) ... this sounds like you have misconfigured your webserver's root or to less probability your kirby config.

Do other pages in the kirby site and the kirby panel work as expected?

Can you see what is exactly coming down the wire (because you have provided above does not give enough information and I guess it is an error page from the webserver). i.e. something like:

```
curl -v --resolve 'localhost:8888:127.0.0.1' http://localhost:8888/sitemap.xsl
```

And, normally `/sitemap.xml` is the main target because `/sitemap.xsl` is only needed when a browser tries to make a pretty render of `/sitemap.xml`.

**Comment by Werbschaft** [comment]
Hi omz13,

thanks for your reply. The /dev folder is only for development, there are many other folders in my localhost folder. And yes, all other things, no matter if Kirby, Plugins, Joomla, WP ist running well. I also tried to set the .htaccess to another RewriteBase but without any success.

The above Command outputs this:

```
* Added localhost:8888:127.0.0.1 to DNS cache
* Hostname localhost was found in DNS cache
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /sitemap.xsl HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Wed, 27 Mar 2019 17:32:11 GMT
< Server: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
< Content-Length: 209
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /sitemap.xsl was not found on this server.</p>
</body></html>
* Connection #0 to host localhost left intact
```

**Comment by omz13** [comment]
The plugin hooks into /sitemal.xml and /sitemap.xsl. So if you are running in subfolder (/dev) it probably won’t work, unless you do some nifty url rewriting.

**Comment by omz13** [comment]
Closing. Reopen if you still have this issue and can provide more information.
