### ISSUE TITLE
standalone zip file

### ISSUE THREAD

**Issue by bnomei** [omz13/kirby3-xmlsitemap#5]
consider my composer skript to build a zip file

```json
...
"scripts": {
  "build": "composer update; composer dumpautoload -o;",
  "zip": "rm kirby3-xmlsitemap.zip; composer update; composer remove getkirby/cms; composer dumpautoload -o; zip -r kirby3-xmlsitemap.zip . -x *.git*; composer require getkirby/cms:'dev-master as 3.0.0'; composer dumpautoload -o;"
},
...
```

**Comment by omz13** [comment]
The zip script in composer.json does more-or-less that... except it uses the composer archive facility instead of calling zip.

BTW, I use a release management tool [liip/rmt](https://packagist.org/packages/liip/rmt) to take care of things... the configuration file `.rmt.yml` has the logic, `make release` invokes things (effectively `./RMT` and `composer zip`).
